name: rk_trial_cupertino_store
description: Creating a Store in Cupertino widgets
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  intl: ^0.16.1
  provider: ^4.1.1
  shrine_images: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:
  assets:
    - packages/shrine_images/0-0.jpg